### ISSUE TITLE
You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by DIDoS** [MysticRyuujin/PlexMissingEpisodes#1]
Executing the ps1 (after adding all the configuration needed) results in a an error:

```
You cannot call a method on a null-valued expression.
At PowerShell.ps1:100 char:13
+             [void]$PlexShows[$GUID]["seasons"][$Episode.parentIndex]. ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
```

Do you know what's causing this?

**Comment by MysticRyuujin** [comment]
Well the line in questions is:

`[void]$PlexShows[$GUID]["seasons"][$Episode.parentIndex].Add(@{$Episode.index = $Episode.title})`

So the most likely issue is with `$Episode.parentIndex`

I wonder if for some reason you have an Episode where it's 'parentIndex' is null for some reason...

You could add this above that line (#100) to check:

```
if ($Episode.parentIndex -eq $Null) {
    $Episode
}
```

That would spit back the entire episode in question....alternatively you could write it in a try catch

```
    try {
        [void]$PlexShows[$GUID]["seasons"][$Episode.parentIndex].Add(@{$Episode.index = $Episode.title})
    } catch { 
        "GUID: "+$GUID
        $Episode
    }
