### ISSUE TITLE
Broken on API V3

### ISSUE THREAD

**Issue by gorgarp** [MysticRyuujin/PlexMissingEpisodes#11]
This was working fantastically, until a few days ago.

TVDB updated their API, which broke the heck out of this.

Messages such as:
"You cannot call a method on a null-valued expression."

.ps1:190 char:13                                                                    +         if (!($PlexShows[$GUID]["seasons"][$Episode.airedSeason.ToStr ...                                             +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException                                                    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by gorgarp** [comment]
Not sure if you are maintaining this anymore, but just a heads up.

**Comment by MysticRyuujin** [comment]
As far as I can tell the script is working, the problem seems to be TheTVDB API returning episodes with a null value for "airedSeason"

I'll push a fix to ignore such episodes.

**Comment by gorgarp** [comment]
Kind of, however, the results are ignore the "blacklist" function. Meaning, I mark the variable to ignore and it's still showing them.

Also, it's showing things as missing that don't exist... (episode 23 when a show only had 12)

**Comment by MysticRyuujin** [comment]
Bah, alright, I'll look deeper.

**Comment by MysticRyuujin** [comment]
Can you give me an example with screenshots or something? I just ran the script against my library and I can't find any glaring errors.... Are you sure you're not just looking at a miss matched show or something?

**Comment by gorgarp** [comment]
Lol sorry man. Just ringing the bell to warn.

$IgnoreList = @(
    #"The Big Bang Theory"
    #"Dirty Jobs"
    #"Street Outlaws"
	"Animaniacs"
	"Blue's Clues"
	"Dexter's Laboratory"
	"LEGO Ninjago: Masters of Spinjitzu"
	"Octonauts"
	"The Octonauts"
	"Paw Patrol"
	"Phineas and Ferb"
	"Power Rangers"
	"Project Runway"
	"Rusty Rivets"
	"SpongeBob SquarePants"
	"Yo Gabba Gabba!"
	"Baby Einstein"
	"Pok*"
	"Ducktales"
	"Superman: The Animated Series"
	"Daniel Tiger's Neighborhood"
	"Daniel Tiger(`')s Neighborhood"
	"Ned's Declassified School Survival Guide"
	"Ned(`')s Declassified School Survival Guide"
	"Marvel's Avengers Assemble"
	"Marvel(`')s Avengers Assemble"
	"Rocko's Modern Life"
	"Rocko(`')s Modern Life"
	"Doc McStuffins"
	"The Chef Show"
	"Mister Rogers(`') Neighborhood"
	"The Fairly OddParents"
	"Dora the Explorer"
	"Mister Rogers' Neighborhood"
	"Mister Rogers(`') Neighborhood"
	"Mister *"
	"Catherine the Great"
	"Celebrity Deathmatch"
	"Fixer Upper"
	"In Living Color"
	"The Dark Crystal: Age of Resistance"
	"Adventure Time"
	"Beavis and Butt-Head"
	"Ask the Storybots"
	
	
)


Piped output to a text file::
Getting results for Octonauts, episodes that don't exist for "The good place"

not much deeper in logging I can give you? I know it's causing a ####storm over at Plex forums. Want to just hold until they sort out what they are working on?

https://forums.plex.tv/t/notice-metadata-using-tvdb-agent/491272/29

**Comment by gorgarp** [comment]
Update:

I downloaded your latest commits.

While I'm not seeing it ignore blacklisted shows anymore, I'm still getting odd results.

Example 1.

You cannot call a method on a null-valued expression.
**********************.ps1:242 char:13                                                                    +         if (!($PlexShows[$GUID]["seasons"][$Episode.airedSeason.ToStr ...                                             +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException                                                    + FullyQualifiedErrorId : InvokeMethodOnNull                                                                        


Example 2. Output shows these as missing

The Good Place S01E15 - Everything Is Great! (2)
The Good Place S01E15 - Everything Is Great! (2)

Not only is it printing the results twice, that episode doesn't exist on TVDB.

https://www.thetvdb.com/series/the-good-place/seasons/official/1

**Comment by MysticRyuujin** [comment]
So, I really don't know why you're getting the null-valued expression error. I thought I took care of that.

However, what you're seeing is from here:
https://www.thetvdb.com/series/the-good-place/seasons/absolute/1

I'm also not sure why that is what is being returned...

**Comment by gorgarp** [comment]
Yeah, that is very strange....

**Comment by gorgarp** [comment]
Just reporting back. Latest commit ran.

FYI, remove the username and unique ID section, only API is required now.
`API authentication w/o username & key — Released 11/15: You'll need to authenticate with your API key, not your username. You can find your API key here: https://www.thetvdb.com/dashboard/account/apikeys`

Got this:
WARNING: Failed to get Episodes for Seinfeld
Which...I'm guessing is unintended? Some of the newer shows I'm guessing it would happen, if data hadn't populated but Seinfeld is rather old and well known.

Known issues blog post states:
`API Favorites Queries Data Discrepancy: instead of returning series name, returns series ID - Researching | related forum thread`
Which could be the cause of some of this.

**Comment by joaoptc** [comment]
I am using your script and it is fantastic !!!! Many thanks !
But I have a question:
I have those on the ignore list, but I am still getting missing episodes:
"90 Day Fiancé"
"90 Day Fiancé: Before the 90 Days"
"90 Day Fiancé: Happily Ever After?"
"90 Day Fiancé: Pillow Talk"
"90 Day Fiancé: The Other Way"

Any ideas of why?
I am copying the show from the script output itself and adding to the ignore list.
I have tryed removed the accent already (é) and it did not work.
Thanks.

**Comment by RealKanashii** [comment]
> "90 Day Fiancé"
> "90 Day Fiancé: Before the 90 Days"
> "90 Day Fiancé: Happily Ever After?"
> "90 Day Fiancé: Pillow Talk"
> "90 Day Fiancé: The Other Way"

Encoding (Fiancé) or the ":" maybe? Try it without ":". Most of the searchers allow to use "no UTF-8" version of titles or ignore not windows allowed caracters. I tried to look for "90 Day Fiance Before the 90 Days" directly on the site and it can find it so it worksd without the UTF-8 chars.

BTW, @MysticRyuujin I was looking for this script for so long I lost hope to find sometyhing this easy, clean and opensource. 
Thank you so much @MysticRyuujin .

**Comment by qlowell** [comment]
Plex is deprecating the TVDB in favor of Plex TV Series agent. It uses a different format for the GUID. This script will still work on the shows in your library that were connected to the TVDB but not for anything new you added. In order to use that the script would need to be updated to accept either agent. https://support.plex.tv/articles/advanced-setting-plex-tv-series-agent/
