### ISSUE TITLE
The remote server returned an error: (523) Origin Unreachable

### ISSUE THREAD

**Issue by gmadd** [MysticRyuujin/PlexMissingEpisodes#3]
In the last few days I've been getting this error when trying to run the script:

Failed to get TheTVDB API Token:
The remote server returned an error: (523) Origin Unreachable.

Possibly related to this issue?
https://forum.kodi.tv/showthread.php?tid=329331

**Comment by MysticRyuujin** [comment]
Is this still a problem? I can't reproduce...
