### ISSUE TITLE
A null key is not allowed in a hash literal.

### ISSUE THREAD

**Issue by triadcool** [MysticRyuujin/PlexMissingEpisodes#6]
I am receiving the following error when trying to run this script:

A null key is not allowed in a hash literal. At D:\Apps\PlexMissingEpisodes-master\PowerShell.ps1:100 char:76 + ... [$GUID]["seasons"][$Episode.parentIndex].Add(@{$Episode.index = $Epis ... + ~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (System.Collections.Hashtable:Hashtable) [], RuntimeException + FullyQualifiedErrorId : InvalidNullKey

**Comment by MysticRyuujin** [comment]
So, step 1 please re-download the latest master copy, I added some features but I also added a check for null that will spit out the problem Episode there must be something unique about it. Please report it back here.

**Comment by triadcool** [comment]
It seemed to run fine this time.  The only issue I am having is that it seems to close after its done running.  Is it suppose to generate a report document of some kind?

**Comment by MysticRyuujin** [comment]
The simplest answer is to open a powershell window first, then run it.

If you want to export it to a log you can pipe it to a log file with:

c:\path_to_script\script.ps1 | Out-File c:\temp\output.txt
